AWSTemplateFormatVersion: 2010-09-09
Description: Deploys a simple S3 bucket from given parameters.

Parameters:
  AppName:
    Description: Name of the Application.
    Type: String
    Default: sample-santi-cool-app
  Environment:
    Description: Environment for the deployment (dev, qa, pdn)
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - pdn
    ConstraintDescription: Must be a valid environment.
  BucketName:
    Description: Name for the S3 bucket.
    Type: String
    Default: default-bucket-santi
  VersioningConfiguration:
    Description: Describes the versioning state of an Amazon S3 bucket.
    Type: String
    Default: Suspended
    AllowedValues:
      - Suspended
      - Enabled

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !Ref VersioningConfiguration
      Tags:
        - Key: Name
          Value: !Join ["-", [s3-bucket, !Ref AppName, !Ref Environment]]
        - Key: Environment
          Value: !Ref Environment

Outputs:
  Environment:
    Description: Environment of the deploy
    Value: !Ref Environment
  BucketName:
    Description: S3 bucket name
    Value: !Ref MyBucket
  BucketArn:
    Description: S3 bucket arn
    Value: !GetAtt MyBucket.Arn
