# Simple Azure DevOps pipeline to deploy CloudFormation templates
name: $(Build.SourceBranchName)$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: UploadCloudFormationResources
    displayName: Upload the CloudFormation templates to AWS S3 Bucket
    jobs:
      - job: upload_content_to_s3_bucket
        steps:
          - task: S3Upload@1
            inputs:
              awsCredentials: "azure-devops-external-agent-dev"
              regionName: "$(region)"
              bucketName: "cf-template-$(app-name)-$(env)"
              sourceFolder: "ec2/ec2-with-sg/"
              globExpressions: |
                *.json
                *master.cf.yml
              targetFolder: "ec2-with-sg"
              createBucket: true

  - stage: CreateOrUploadCloudFormationStack
    displayName: Create/Upload the CloudFormation Stack
    jobs:
      - job: create_or_upload_cloudformation_stack
        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                echo 'params befor replacement:'
                cat ec2/ec2-with-sg/params.json;
          - task: replacetokens@3
            inputs:
              targetFiles: "**/*.json"
              encoding: "auto"
              writeBOM: true
              actionOnMissing: "warn"
              keepToken: false
              tokenPrefix: "#{"
              tokenSuffix: "}#"
              useLegacyPattern: false
              enableTransforms: false
              enableTelemetry: false
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                echo 'params befor replacement:'
                cat ec2/ec2-with-sg/params.json;
          - task: CloudFormationCreateOrUpdateStack@1
            inputs:
              awsCredentials: "azure-devops-external-agent-dev"
              regionName: "$(region)"
              stackName: "$(stack-name)-$(env)"
              templateSource: "s3"
              s3BucketName: "cf-template-$(app-name)-$(env)"
              s3ObjectKey: "ec2-with-sg/master.cf.yml"
              templateParametersFile: "ec2/ec2-with-sg/params.json"
              capabilityAutoExpand: true
